exclude: ^(resources|tests/resources)/

repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff
        name: Run ruff to auto-fix lint errors
        types_or: [ python, pyi ]
      - id: ruff-format
        name: Run ruff to format code
        types_or: [ python, pyi ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: debug-statements
        language_version: python3

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
    -   id: mypy
        files: ^src/weather/|^tests

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.3
    hooks:
      - id: commitizen
        stages: [commit-msg]

-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.21
    hooks:
    -   id: uv-lock
        name: Update uv lock file

- repo: https://github.com/jsh9/pydoclint
  rev: 0.8.6
  hooks:
    - id: pydoclint
      files: ^src/weather/

- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.24.1
  hooks:
    - id: pyproject-fmt
